### ISSUE TITLE
OTOBO needs to be updated to latest version

### ISSUE THREAD

**Issue by aapeliv** [Couchers-org/tools#1]
Our support / ticket management software, OTOBO needs to be updated to the latest version. Not super urgent, but something that should be taken care of in the near future.

https://otobo.de/en/release-note-otobo-10-0-11/

Copied from: https://github.com/Couchers-org/couchers/issues/1651

**Comment by aapeliv** [comment]
@AllhandsNoFeet

**Comment by AllhandsNoFeet** [comment]
Latest version is now https://otobo.de/en/otobo-10-0-15/
