### ISSUE TITLE
The help center is not accessible anymore

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/tools#11]
It is not possible to access the help center via https://help.couchers.org/ or via the Chatwoot portal https://chatwoot.couchershq.org/app/accounts/2/portals

The error message on the public page is:

![image](https://github.com/user-attachments/assets/fd512e1b-ac8f-4f3a-acad-91cbfecff998)

**Comment by aapeliv** [comment]
Fixed. Needed to run migrations...
