### ISSUE TITLE
Update Chatwoot to 3.15.0

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/tools#12]
Several important bugfixes in this release, so this upgrade is kinda urgent

https://github.com/chatwoot/chatwoot/releases

**Comment by nabramow** [comment]
@aapeliv I think you did this too?

**Comment by jesseallhands** [comment]
He did it and it's upgraded now. But in the process our Gmail account got disconnected. I'll close this and create a new ticket for the mail account disconnection issue.

**Comment by aapeliv** [comment]
Mail is fixed
