### ISSUE TITLE
emails to volunteers@couchers.org don't land in Chatwoot

### ISSUE THREAD

**Issue by jesseallhands** [Couchers-org/tools#13]
I suspect these emails are getting stuck in support@couchers.org gmail account and aren't being forwarded for some reason. 

Or perhaps they are being stuck somewhere else.... I'm pretty sure volunteers@couchers.org is an alias

**Comment by aapeliv** [comment]
It’s a mailing list proper: 
![IMG_7382](https://github.com/user-attachments/assets/df5fe55e-426f-46de-9791-3895e74465fe)

**Comment by aapeliv** [comment]
I added you to the list
